
// Static list of generic saving tips to replace AI
const TIPS_LIBRARY = [
  "Create a monthly budget and stick to it strictly.",
  "Track every single expense for 30 days to identify leaks.",
  "Cook at home more often; eating out is a major budget drain.",
  "Bring your lunch to work instead of buying it daily.",
  "Make your own coffee at home instead of visiting cafes.",
  "Always shop with a grocery list and do not deviate.",
  "Buy generic store brands instead of expensive name brands.",
  "Shop for groceries on a full stomach to avoid impulse buys.",
  "Buy non-perishable items in bulk when they are on sale.",
  "Use digital coupons and cashback apps for everyday purchases.",
  "Cancel streaming subscriptions you haven't watched in a month.",
  "Review your bank statements weekly to catch errors or subscriptions.",
  "Set up automatic transfers to your savings account on payday.",
  "Use the 24-hour rule: wait a day before making any non-essential purchase.",
  "Pay off high-interest debt (like credit cards) first.",
  "Use the envelope method for discretionary spending categories.",
  "Call your internet and insurance providers to negotiate lower rates.",
  "Turn off lights when you leave a room to lower electricity bills.",
  "Unplug electronics (vampire appliances) when not in use.",
  "Switch to LED light bulbs for long-term energy savings.",
  "Adjust your thermostat by 2 degrees to save on heating/cooling.",
  "Wash clothes in cold water to save on water heating costs.",
  "Air dry your clothes instead of using the dryer when possible.",
  "Walk or bike for short trips instead of driving.",
  "Use public transportation to save on gas and parking.",
  "Carpool with coworkers or friends to split fuel costs.",
  "Check tire pressure regularly; proper inflation improves gas mileage.",
  "Shop around for cheaper car insurance rates every year.",
  "Borrow books and movies from the public library instead of buying.",
  "Look for free community events for entertainment.",
  "Host potluck dinners instead of meeting friends at expensive restaurants.",
  "Cancel cable TV and switch to a cheaper single streaming service.",
  "Buy second-hand clothes and furniture from thrift stores or marketplaces.",
  "Sell items you no longer need on online marketplaces.",
  "Learn to do minor repairs on household items instead of replacing them.",
  "Make DIY gifts for holidays instead of buying expensive store items.",
  "Meal plan for the entire week to reduce food waste.",
  "Drink water instead of purchasing soda, juice, or bottled drinks.",
  "Take advantage of any employer matching for retirement accounts.",
  "Open a high-yield savings account for your emergency fund.",
  "Set specific financial goals (e.g., 'Save $1000 for vacation').",
  "Avoid impulse buying by deleting shopping apps from your phone.",
  "Compare prices online before making any major purchase.",
  "Wait for major holiday sales to buy electronics or appliances.",
  "Install a programmable thermostat to regulate energy usage automatically.",
  "Seal air leaks around windows and doors to reduce drafts.",
  "Plant a small garden to grow your own herbs or vegetables.",
  "Learn basic sewing to mend clothes instead of discarding them.",
  "Consider cutting your own hair or swapping haircuts with a skilled friend.",
  "Exercise at home or outdoors instead of paying for a gym membership.",
  "Use vinegar and baking soda for cheap, effective cleaning solutions.",
  "Revisit your budget every month to adjust for changing expenses.",
  "Switch to a prepaid or cheaper cell phone plan.",
  "Refinance your mortgage or student loans if rates drop.",
  "Use a rewards credit card but pay the balance in full every month.",
  "Avoid late fees by setting up calendar reminders for bill due dates.",
  "Challenge yourself to a 'no-spend' weekend once a month.",
  "Pack snacks and water when running errands to avoid convenience store purchases.",
  "Buy seasonal produce; it is cheaper and tastes better.",
  "Freeze leftovers immediately so they don't go bad.",
  "Use gas price apps to find the cheapest fuel in your area.",
  "Always check for a promo code before checking out online.",
  "Unsubscribe from marketing emails to reduce temptation.",
  "Keep your car well-maintained to avoid costly repairs later.",
  "Change your home air filters regularly to keep your HVAC efficient.",
  "Use a clothesline or drying rack to save on dryer energy.",
  "Take shorter showers to reduce water and heating bills.",
  "Fix leaky faucets immediately; a drip costs money over time.",
  "Install a low-flow showerhead to reduce water usage.",
  "Buy quality items that last longer rather than cheap items that break often.",
  "Barter services with friends (e.g., pet sitting for plant watering).",
  "Use the library for printing instead of buying ink and paper.",
  "Make your own household cleaners.",
  "Limit alcohol consumption when dining out; it has a high markup."
];

export const getSavingTips = async (expenseDescription: string): Promise<string[]> => {
  // Simulate network delay for realism
  await new Promise(resolve => setTimeout(resolve, 800));

  // Logic: Shuffle array and pick 3
  const shuffled = [...TIPS_LIBRARY].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 3);
};
